CREATE TYPE status AS ENUM ('Not Started', 'Completed', 'In Progress');

create table users (
  id bigint generated by default as identity primary key,
  username text,
);

create table tasks (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  title text,
  desc text,
  status status
  due_date date
);
